### ISSUE TITLE
`poster` not declared as a dependency in setup.py

### ISSUE THREAD

**Issue by timClicks** [socrata-archive/socrata-python-deprecated#2]
`poster` isn't listed as a dependency. This means that setuptools doesn't install the socrata package properly.

```
>>> from Socrata import Dataset
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "Socrata.py", line 19, in <module>
    from poster.encode import multipart_encode
ImportError: No module named poster.encode
```

**Comment by ascandella** [comment]
Tim,

Thanks for pointing this out. We'll hopefully be overhauling these libraries soon, but in the mean time I've added the necessary information to setup.py.
