### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by nicktimko** [socrata-archive/socrata-python-deprecated#9]
If I may be so bold, why is the Python Socrata library deprecated? Should we just make our own functions with `urllib` and `json`? Nobody on the Socrata team uses Python and the 2.0 API broke what's here?

If someone were to update the API, could it be lifted out of the pit of ~~despair~~ depreciation? The lack of Python support seems like a sucking chest wound.

**Comment by chrismetcalf** [comment]
@nicktimko A long time in a galaxy far-far away we created this (somewhat rudimentary) Python library against the old 1.0 version of our API, but it fell into disrepair even before we released [SODA 2.0](http://dev.socrata.com/consumers/getting-started.html) and [SoQL](http://dev.socrata.com/docs/queries.html). I just didn't feel comfortable calling it an officially-supported library anymore.

Don't let that lead you to believe we're a bunch of Python-hating Rubyists or something - a new Python library has been on our roadmap for awhile but we've been focusing on some other projects. I've actually hacked up a few things accessing the API via the `urllib2` and `json` libraries, but I'm just not enough of a ninja with Python yet to feel comfortable taking on a fully documented SODA library.

If you'd like to help <strike>bandage our sucking chest wound</strike> write a modern Python library for SODA 2.0, I'd be glad to help in any way I can and proud to list it as a community-supported library on our [dev site](http://dev.socrata.com/libraries/).

**Comment by hydrosquall** [comment]
Following up: went looking for a library and found these two:
- Listed on the official dev site - [sodapy](https://github.com/xmunoz/sodapy)
- Not listed but has fewer dependencies [soda2-python](https://github.com/cjmaynar/soda2-python) 

Will check both of them out, curious if people have found any additional ones supporting the 2.0 API

**Comment by chrismetcalf** [comment]
@hydrosquall Yep, https://github.com/xmunoz/sodapy is your best bet at this point. @xmunoz is a good guy too.
